version: "3"

services:
  samba:
    container_name: samba
    image: dperson/samba
    ports:
      - "139:139/tcp"
      - "445:445/tcp"
    environment:
      TZ: 'America/Detroit'
      SHARE: "NAS;/share;yes;no;no;all;pi;pi]"
      USER: "pi;${SAMBA_PI_PASSWORD}"
    volumes:
      - '${SAMBA_VOLUME_SHARE}:/share'
    restart: unless-stopped
